on: [push]
name: Tests
jobs:
    setup-and-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            -   name: Composer install
                run: composer install --no-interaction --no-progress

            -   name: Run Code Standards
                run: vendor/bin/phpcs

            -   name: Run Unit Tests
                run: vendor/bin/phpunit tests/Unit

            -   name: Run Integration Tests
                run: vendor/bin/phpunit tests/Feature
